
# This is a basic workflow to help you get started with Actions
name: bump cargo minor version
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ stable ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    cargo_version_bump:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Bump minor version
          run: |
            # Get the current version
            VERSION=$(grep -oP '^version = "\K[0-9]+\.[0-9]+\.[0-9]+' Cargo.toml)
            # Bump the minor version
            NEW_VERSION=$(echo $VERSION | awk -F "." '{print $1"."$2"."($3+1)}')
            # Replace the old version with the new version
            sed -i "s/^version = \"$VERSION\"/version = \"$NEW_VERSION\"/" Cargo.toml
          shell: bash
        - name: Commit and push changes
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git tag -a v$NEW_VERSION -m "Bump minor version to $NEW_VERSION"
            git commit -a -m "Bump minor version to $NEW_VERSION"
            git push origin HEAD --follow-tags
